### PR TITLE
#1168: Fix for [PW-5546] Error: Call to undefined method PayPal\Brain…

### PR DESCRIPTION
**Pull request by diazwatson**
**Description**

Changes the module sequence to fix the raise condition generated when Paypal also tries to set a preference.
**Tested scenarios**

**Fixed issue**:  
https://github.com/Adyen/adyen-magento2/issues/1168

Credit goes to @cmtickle

### CODE REVIEW

**Comment by diazwatson** [comment]
Hi @acampos1916 from what I see, #1182 does not solve the issue Commerce users face when installing the module.
It means the module will be still broken for everyone on Magento Commerce. 🤔

**Comment by acampos1916** [comment]
Thanks @diazwatson, we'll check it out and will come back to you.

**Comment by acampos1916** [comment]
@diazwatson we're going to apply your suggested fix and will later move the state data clean to a cron to remove the module sequence completely, thanks!

**Comment by diazwatson** [comment]
Hey @acampos1916 I think Magento will just skip this sequence if modules:

- Amazon_Core
- PayPal_Braintree

are not present in the target installation, also neither of these modules is something Adyen module needs to work, so I don't think these need to be included in the composer file as dependencies.

**Comment by acampos1916** [comment]
Closing this PR now as it has been addressed with #1192

**Pull request closed without merging**
