### PR TITLE
[PW-6325] - Use formattedBillingAddress for AmazonPay for the virtual products

### PR DESCRIPTION
**Pull request by candemiralp**
**Description**

Use `formattedBillingAddress` for AmazonPay for the virtual product `addressDetails`

**Tested scenarios**

AmazonPay

### CODE REVIEW

**Review by michaelpaul — APPROVED** [review]

**Review by tnaber — CHANGES_REQUESTED** [review]
Wouldn't it be better to set a variable address to either formattedBillingAddress or formattedShippingAddress and then configure the addressDetails based on that variable? 
Additionally, what happens when there is no address available? (I guess it just throws an error based on the empty addressDetails in the config right? That's probably fine then)

**Comment by candemiralp** [comment]
> 

@tnaber As a part of this ticket, creating a follow-up ticket related to convert all the address fields to billing address instead of shipping address has already been planned. After that follow-up, we will use one address for all of the payment method. 

For additional question, billing address is coming from user details, so it won't be empty in any case.

**Review by tnaber — APPROVED** [review]

**Comment by AlexandrosMor** [comment]
@candemiralp make sure that you test the declined flow for amazon pay

**Comment by candemiralp** [comment]
> @candemiralp make sure that you test the declined flow for amazon pay

I will test declined flow before merging this branch. Thanks @AlexandrosMor!

**Pull request merged**
