### PR TITLE
add mixin that refresh payment methods list after quote save

### PR DESCRIPTION
**Pull request by ZebraBeard**
**PROBLEM:**

When the user selects a shipping method with a price > 0, he will get an error message on the Apple Pay payment method.

If you will refresh the page after shipping method selection, everything gonna works as expected.

**EXPECTED RESULT:**

Apple Pay payment should proceed with any shipping method.

**HOW TO RECREATE:**

Open Safari and go to website
Add any product to the cart
Go to checkout, and fulfil address information
Select a shipping method that have a price of more than zero
Click 'Continue' and select Apple Pay as a payment method.
Click Pay, and after that, you will see a popup with a payment confirmation that has the wrong subtotal
Confirm a payment, and after that, you will see an error.

**ADDITIONAL INFO:**

This issue happens because Apple Pay requires an order amount to be included in the request to get a payment methods list. It takes this amount from the quote, and the quote is updating it only on set-shipping-information action that happens after clicking on the Continue button. And Adyen sends the request to get payment methods before that. So in the end Magento will send the wrong order amount.

The bug was found in Magento 2.3.4-p2 and Adyen module 7.1

### CODE REVIEW

**Comment by cyattilakiss** [comment]
Hi @ZebraBeard ,

Thank you for the contribution, we are going to test and review the code at first. Thanks for the elaborate description about the issue as well!

Have a great weekend!
Attila
Adyen

**Comment by ZebraBeard** [comment]
Hi, @cyattilakiss @peterojo is there any updates on this? 
This issue is critical, and I feel that it needs to be reviewed a bit faster. Is there anything that I can help you with?

**Comment by Morerice** [comment]
> Hi, @cyattilakiss @peterojo is there any updates on this?
> This issue is critical, and I feel that it needs to be reviewed a bit faster. Is there anything that I can help you with?

Hi @ZebraBeard 

Apologies for our late reply. We are currently reviewing your solution. If approved it will be included in the next release.

Best regards,
Jean
Adyen

**Review by Morerice — APPROVED** [review]

**Review by peterojo — APPROVED** [review]

**Comment by jonathanribas** [comment]
Hi @ZebraBeard @Morerice, 

1/ New source code from this MR is not compatible with this fix https://github.com/Adyen/adyen-magento2/pull/1094

On a store without Adyen payment methods, we can't play any orders.

2/ This new code also calls a lot of time Adyen retrieve payment methods webservice. In terms of performance it's not good and blocking checkout rendering (which is slow by nature).

**Pull request merged**
