### PR TITLE
Compatibility with PHP 8 and Magento 2.4.4

### PR DESCRIPTION
**Pull request by KluseG**
**Description**
Fix:
* Fatal error: Declaration of Adyen\Payment\Logger\Handler\AdyenBase::isHandling(array $record) must be compatible with Monolog\Handler\AbstractHandler::isHandling(array $record): bool in vendor/adyen/module-payment/Logger/Handler/AdyenBase.php on line 35
* Fatal error: Declaration of Adyen\Payment\Logger\AdyenLogger::addRecord($level, $message, array $context = []) must be compatible with Monolog\Monolog\Logger::addRecord($level, $message, array $context = []): bool in vendor/adyen/module-payment/Logger/AdyenLogger.php on line 103

**Tested scenarios**
Running `bin/magento setup:upgrade`

**Fixed issue**:  #1264

### CODE REVIEW

**Review by Morerice — APPROVED** [review]

**Comment by Morerice** [comment]
Hi @KluseG,

Thanks for opening this PR!

Regards,
Jean
Adyen

**Review by candemiralp — APPROVED** [review]

**Comment by manaftryzens** [comment]
Hi,

Can we get this released ? When we can expect a new version with this fix included? We are currently trying to install the module on 2.4.4 magento and the issue exists.

Thanks,
Manaf

**Comment by manaftryzens** [comment]
Hi,
When 8.2.1 will be available for install? We can't see this tag published when we try to install adyen via composer.

**Comment by Morerice** [comment]
> Hi, When 8.2.1 will be available for install? We can't see this tag published when we try to install adyen via composer.

Hi @manaftryzens,

v8.2.1 will be released tomorrow (19/04/22)

Best regards,
Jean
Adyen

**Comment by manaftryzens** [comment]
> 

Hey @Morerice ,

Thanks a lot.
We are excited to see the changes and get it working 

Regards,
Manaf

**Pull request merged**
