### PR TITLE
PW-514 Invoice on shipment option for openinvoice payment methods

### PR DESCRIPTION
**Pull request by rikterbeek**
**Description**

If setting enabled it is possible to auto invoice payments on shipment for openinvoice payment methods. (Klarna,AfterPay and RatePay)
**Tested scenarios**

**Fixed issue**:

### CODE REVIEW

**Comment by anup4ranium** [comment]
@rikterbeek Does it cater for partial shipments and creates partial invoice ?
If not , then ideally it should create invoice only when all items of order are shipped .

**Comment by rikterbeek** [comment]
Hi @anup4ranium,

No works only for full invoices. Do you know easily how to support partial captures ?

Regards,
Rik
Adyen

**Comment by anup4ranium** [comment]
@rikterbeek  We have implemented it as below : 

1. Added hook on **sales_order_shipment_save_after** event
2. Creating Invoice when `shipped-items == ordered-items`

**Comment by rikterbeek** [comment]
Hi @anup4ranium,

I want to do it before shipment as if invoice failed there will be no shipment. For now this cover a use-case of a customer ideally this is beging handled by the warehouse solution.

Regards,
Rik
Adyen

**Comment by anup4ranium** [comment]
Hi @rikterbeek  

Makes sense to halt shipment if Invoice fails 👍 
But its true that here capture can happen before ALL items are shipped in case of partial shipments. 
Not sure if it is acceptable legally with different open-invoice payment providers.

Thanks

**Pull request merged**
