### PR TITLE
Show payment link in admin for remaining order balance

### PR DESCRIPTION
**Pull request by Maikel-Koek**
This link only shows when the original order payment method is an
Adyen method, the total due is greater than 0 and the invoiced total
is greater than 0.

Solves #254.

Payment info at order in backend:

schermafbeelding 2018-02-22 om 15 12 57

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

Looking good. I would say only to do an extra check to only show it when the payment method was adyen_hpp could you add that ?


Regards,
Rik
Adyen

**Comment by Maikel-Koek** [comment]
Hi @rikterbeek ,

We actually discussed that statement here (@paales), and we thought the opposite, to even remove it completely, so show the remainder payment link for every payment method.

Why would you only want to show it when an HPP method was used?

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

Problem that can occur is that adyen_HPP needs to be configured otherwise it will fail the payment link. Maybe we can say if adyen_paybymail and adyen_hpp are enabled to show it? as well you do not want to show the button if a card payment is reserved but the invoice is not created (in a auth/cap flow the invoice will be generated on capture payment).

Regards,
Rik
Adyen

**Comment by Maikel-Koek** [comment]
Hi @rikterbeek,

I see, I can add a check if those methods are enabled, but not necessarily used on the order.

To prevent it from showing when a card payment is pending, I check the `total invoiced > 0 AND total due > 0`, which I think will suffice for most cases? Because most order payments are made at once? Which will have a total invoiced of zero.

**Pull request merged**
