### PR TITLE
GraphQl - Add saveStateData mutation

### PR DESCRIPTION
**Pull request by dimitriBouteille**
Add `saveAdyenStateData` mutation.

### CODE REVIEW

**Comment by lewisvoncken** [comment]
@dimitriBouteille 

I have another solution which doesn't require an additional GraphQL to save the data.

https://github.com/Adyen/adyen-magento2/compare/develop...lewisvoncken:adyen-magento2:patch-1

**Comment by dimitriBouteille** [comment]
I think this mutation is required. 
In my case, the [setPaymentMethodOnCart](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/set-payment-method/) and [placeOrder](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/place-order/) mutation are not executed in same time ...

**Comment by lewisvoncken** [comment]
Hi @dimitriBouteille 

I had the same issue that the setPaymentMethodOnCart is separate from the placeOrder and with the change it saves it to the database when it selects the payment method in the setPaymentMethodOnCart.

This means that I only execute the setPaymentMethodOnCart mutation and later the placeOrder which reduces the GraphQLs from 3 to 2.

**Comment by dimitriBouteille** [comment]
@lewisvoncken I didn’t really understand how `setStateData` works, but now it’s clearer :)

**Pull request closed without merging**
