### PR TITLE
Check order invoice email configuration in Magento before sending the email after processing a webhook

### PR DESCRIPTION
**Pull request by aschrammel**
**Description**
The plugin now checks the order invoice email configuration in Magento before sending order invoice emails after processing webhooks. Previously, invoice emails were sent without checking the configuration value, and an email was sent twice when the configuration was enabled. 

**Tested scenarios**
Order invoice emails are only sent if the corresponding configuration is activated in Magento.

### CODE REVIEW

**Comment by candemiralp** [comment]
Hello @aschrammel,

Thank you for your contribution. We will check the PR and merge it if there is no issue.

Best Regards,
Can

**Review by acampos1916 — APPROVED** [review]

**Comment by aschrammel** [comment]
Hi @candemiralp 😄 

Do you maybe have an update on that one?

**Review by candemiralp — APPROVED** [review]

**Comment by candemiralp** [comment]
Hello @aschrammel,

Thank you for your contribution. Your patch has been merged and will be released today.

Best Regards,
Can

**Comment by aschrammel** [comment]
Hi @candemiralp 

Thanks a lot for the update and merging the issue.

Merry Christmas and a Happy New Year.

Best regards
Andreas

**Pull request merged**
