### PR TITLE
Added new column processing to adyen notification table to know if no…

### PR DESCRIPTION
**Pull request by shruti-ranium**
…tification record is already processing under other cron-job

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi @shruti-ranium,

Thanks for the PR!  I was looking if Magento2 has an option for mass-update but it looks like that is not possible. The two foreach loop would something that would be nice to resolve.

Could you make the version to 2.0.7 and the updates to this version so on the upgrade from 2.0.6 all users this execute will take place ?

Regards,
Rik
Adyen

**Comment by shruti-ranium** [comment]
Hi Rik,

I have made the version changes .


Thanks,
Shruti

**Comment by rikterbeek** [comment]
Hi @shruti-ranium,

Thanks for the change I merged it into the code.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @shruti-ranium,

Saw this was causing issues with recurring_contract notifications so I made the following fix see below.

Regards,
Rik
Adyen

**Pull request merged**
